//
//  NetworkingService.swift
//  Keto-Chef
//
//  Created by Ricardo Rodriguez on 3/20/19.
//  Copyright © 2019 Ricardo Rodriguez. All rights reserved.
//

import Foundation
import Firebase
import FirebaseDatabase

class NetworkingService {
    
    func saveRecipe(recipe: Recipe) {
        //Getting the reference to the database
        var ref: DatabaseReference!
        ref = Database.database().reference()
        
        // Getting an autogenerated ID, this will be super useful to handle unique items every time and Firebase takes care of it.
        let key = ref.child("recipes").childByAutoId().key
        
        // Saving the data we'll send in a dictionary
        let newItem: [String: Any] = ["name": recipe.recipeName,
                       "description": recipe.recipeDescription,
                       "ingredients": recipe.recipeIngredients,
                       "directions": recipe.recipeDirections]
        
        // Method from Firebase library that creates a new entry.
        ref.child("recipes").child(key!).setValue(newItem)

    }

    
    
}
